import re
import arxiv

author_file = "authors.txt"
paper_file = "papers.txt"
outfile = open("../../_pages/papers.html", "w")
linkstyle = r""" <a href="{0}" target="_blank"><span style="font-family: sans-serif, 'Open Sans';color: #999;font-size: 15px;">({1})</span></a>"""
normal_link = r"""<a href="{0}" target="_blank">{1}</a>"""
abstract_format = r"""<details> <summary><b>Abstract</b></summary>
{0}
</details>"""

def get_lines(filepath):
	with open(filepath, 'r') as f:
		L = f.readlines()
	return [s.rstrip() for s in L]

def file_to_dict(filepath):
	L = get_lines(filepath)
	d = {}
	current = None
	start_new = True

	for i in range(len(L)):
		if start_new:
			current = L[i]
			d[current] = {}
			start_new = False
			continue

		if len(L[i]) == 0: continue

		if len(L[i]) > 0 and L[i][0] == "=":
			start_new = True
			if current == "ignore":
				del d[current]
			continue

		s = L[i]
		key, value = s.split(":", 1)
		key = key.strip()
		value = value.strip()

		d[current][key] = value
	return d

def add_newline(s):
	return s + " <br>\n"

def dollars_to_brackets(s, slashes = 1):
	assert slashes in [1, 2], "Haven't implemented!"
	bracketed = r'\\\(\1\\\)' if slashes == 2 else r'\(\1\)'
	return re.sub(r'\$(.*?)\$', bracketed, s)

authors = file_to_dict(author_file)
papers = file_to_dict(paper_file)

preamble = r"""---
layout: archive
title: "Papers"
permalink: /papers/
author_profile: true
---

Listed in (reverse chronological) order of first upload to arXiv (recentmost first).  <br>
<a href="https://arxiv.org/a/maithani_a_1.html" target="_blank">My arXiv author page</a>
<!-- generated by /math/codes/papers_page_generator/generator.py -->
"""

def printt(*args):
	print(*args, file=outfile)
	outfile.flush()
	# print(*args)

def coauthor_code(author):
	s = author['name']
	if 'webpage' in author:
		s = normal_link.format(author['webpage'], s)
	return s

printt(preamble)
N = len(papers)
for _, paper in papers.items():
	s = "<p>\n"
	s += f"{N}. "
	N -= 1

	s += f"<b>{dollars_to_brackets(paper['title'])}</b>"
	s = add_newline(s)

	arxiv_paper = None
	if 'arxiv' in paper:
		paper_id = paper['arxiv']
		link = r"""https://arxiv.org/abs/""" + paper_id
		s += linkstyle.format(link, "arXiv")
		arxiv_paper = next(arxiv.Client().results(arxiv.Search(id_list=[paper_id])))

	if 'pdf' in paper:
		link = paper['pdf'] + ".pdf"
		s += linkstyle.format(link, "PDF")

	if 'jour-link' in paper:
		link = paper['jour-link']
		s += linkstyle.format(link, "Journal")

	if 'mr' in paper:
		link = r"""https://mathscinet.ams.org/mathscinet/article?mr=""" + paper['mr']
		s += linkstyle.format(link, "MathSciNet")

	if "coauthors" in paper:
		s = add_newline(s)
		coauthors = paper['coauthors'].split(",")
		coauthors = [coauthor_code(authors[c.strip()]) for c in coauthors]
		if len(coauthors) > 1:
			coauthors[-1] = f"and {coauthors[-1]}"
		if len(coauthors) == 2:
			coauthors = f"{coauthors[0]} {coauthors[1]}"
		else:
			coauthors = ", ".join(coauthors)
		s += f"with {coauthors}"

	citation = None
	if "journal" in paper:
		citation = paper["journal"]
		if "volume" in paper:
			citation += f" <b>{paper['volume']}</b>"
			if "issue" in paper:
				citation += f"({paper['issue']})"

			assert "year" in paper, "Volume but no year!"
			citation += f" ({paper['year']}), "

			assert "pages" in paper or "article" in paper, "Lack of identification!"
			if "article" in paper:
				citation += f"article no. {paper["article"]}"
			else:
				citation += paper["pages"]

	if citation:
		s = add_newline(s)
		s += citation

	if "toa" in paper:
		s = add_newline(s)
		s += paper["toa"] + " (To appear)"

	if arxiv_paper is not None:
		abstract = arxiv_paper.summary
		s = add_newline(s)
		s += abstract_format.format(abstract)

	s += "\n</p>\n"
	printt(s)