import re

author_file = "authors.txt"
paper_file = "papers.txt"
outfile = open("../../_pages/papers.md", "w")
linkstyle = r""" <a href="{0}" target="_blank"><span style="font-family: sans-serif, 'Open Sans';color: #999;font-size: 15px;">({1})</span></a>"""

def get_lines(filepath):
	with open(filepath, 'r') as f:
		L = f.readlines()
	return [s.rstrip() for s in L]

def file_to_dict(filepath):
	L = get_lines(filepath)
	d = {}
	current = None
	start_new = True

	for i in range(len(L)):
		if start_new:
			current = L[i]
			d[current] = {}
			start_new = False
			continue

		if len(L[i]) > 0 and L[i][0] == "=":
			start_new = True
			if current == "ignore":
				del d[current]
			continue

		s = L[i]
		key, value = s.split(":", 1)
		key = key.strip()
		value = value.strip()

		d[current][key] = value
	return d

def add_newline(s):
	return s + " " * 2 + "\n"

def dollars_to_brackets(s):
	return re.sub(r'\$(.*?)\$', r'\\\(\1\\\)', s)

authors = file_to_dict(author_file)
papers = file_to_dict(paper_file)

preamble = r"""---
layout: archive
title: "Papers"
permalink: /papers/
author_profile: true
---

Here are my preprints, listed in (reverse chronological) order of first upload to arXiv (recentmost first).  
[My arXiv author page](https://arxiv.org/a/maithani_a_1.html)
<!-- generated by /math/codes/papers_page_generator/generator.py -->
"""

def printt(*args):
	print(*args, file=outfile)
	outfile.flush()
	# print(*args)

def coauthor_code(author):
	s = author['name']
	if 'webpage' in author:
		s = f"[{s}]({author['webpage']})"
	return s

printt(preamble)
N = len(papers)
for _, paper in papers.items():
	s = f"{N}\\. "
	N -= 1

	s += f"<b>{dollars_to_brackets(paper['title'])}</b>"
	s = add_newline(s)

	if 'arxiv' in paper:
		link = r"""https://arxiv.org/abs/""" + paper['arxiv']
		s += linkstyle.format(link, "arXiv")

	if 'pdf' in paper:
		link = paper['pdf'] + ".pdf"
		s += linkstyle.format(link, "PDF")

	if 'journal' in paper:
		link = paper['journal']
		s += linkstyle.format(link, "Journal")

	if 'mr' in paper:
		link = r"""https://mathscinet.ams.org/mathscinet/article?mr=""" + paper['mr']
		s += linkstyle.format(link, "MathSciNet")

	if "coauthors" in paper:
		s = add_newline(s)
		coauthors = paper['coauthors'].split(",")
		coauthors = [coauthor_code(authors[c.strip()]) for c in coauthors]
		if len(coauthors) > 1:
			coauthors[-1] = f"and {coauthors[-1]}"
		if len(coauthors) == 2:
			coauthors = f"{coauthors[0]} {coauthors[1]}"
		else:
			coauthors = ", ".join(coauthors)
		s += f"with {coauthors}"

	if "cite" in paper:
		s = add_newline(s)
		s += paper["cite"]

	s += "\n"
	printt(s)